const mongoose = require('mongoose');

const newhireSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  employeeId: { type: String, unique: true, sparse: true },
  role: { type: String, enum: ['admin','hr','employee'], default: 'employee' },
  name: String,
  email: { type: String, sparse: true },
  mobile: String,
  title: String,
  firstName: String,
  lastName: String,
  knownAs: String,
  dob: String,
  age: String,
  nationality: String,
  workCountry: String,
  gender: String,
  maritalStatus: String,
  pan: String,
  fatherName: String,
  motherName: String,
  passportNo: String,
  designation: String,
  grade: String,
  department: String,
  permAddress1: String,
  permAddress2: String,
  permAddress3: String,
  permPincode: String,
  permState: String,
  permCountry: String,
  corrAddress1: String,
  corrAddress2: String,
  corrAddress3: String,
  corrPincode: String,
  corrState: String,
  corrCountry: String,
  edu1_est: String,
  edu1_inst: String,
  edu1_ctry: String,
  edu1_cert: String,
  edu1_branch: String,
  edu1_score: String,
  edu1_start: String,
  edu1_end: String,
  edu2_est: String,
  edu2_inst: String,
  edu2_ctry: String,
  edu2_cert: String,
  edu2_branch: String,
  edu2_score: String,
  edu2_start: String,
  edu2_end: String,
  edu3_est: String,
  edu3_inst: String,
  edu3_ctry: String,
  edu3_cert: String,
  edu3_branch: String,
  edu3_score: String,
  edu3_start: String,
  edu3_end: String,
  exp1_org: String,
  exp1_des: String,
  exp1_ind: String,
  exp1_city: String,
  exp1_ctry: String,
  exp1_start: String,
  exp1_end: String,
  exp2_org: String,
  exp2_des: String,
  exp2_ind: String,
  exp2_city: String,
  exp2_ctry: String,
  exp2_start: String,
  exp2_end: String,
  exp3_org: String,
  exp3_des: String,
  exp3_ind: String,
  exp3_city: String,
  exp3_ctry: String,
  exp3_start: String,
  exp3_end: String,
  decName: String,
  decSign: String,
  decDate: String,
  createdAt: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model('NewHire', newhireSchema);
